
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND AS BREAK COMMA DEF DEQUALS DIC DIFFERENT DIVIDE DIVIDEINT ELIF ELSE EQUALS EXPONENT FALSE FOR FROM HIGHER HIGHEREQ IF IMPORT IN IS LCORCHETE LEN LESS LESSEQ LIST LPAREN MINUS MODULE NAME NONE NOT NUMBER OR PLUS PRINT RANGE RCORCHETE RETURN RPAREN SET THEN TIMES TRUE TUPLE WHILEassign : NAME EQUALS exprexpr : expr PLUS term\n\t\t\t| expr MINUS term\n\t\t\t| termterm : term TIMES factor\n\t\t\t| term DIVIDE factor\n\t\t\t| factorassign : NAME EQUALS listlist : LCORCHETE RCORCHETE\n\t\t\t| LCORCHETE element RCORCHETEelement : factorfactor : NUMBER'
    
_lr_action_items = {'NAME':([0,],[2,]),'$end':([1,4,5,6,8,9,14,17,18,19,20,21,],[0,-1,-8,-4,-7,-12,-9,-2,-3,-5,-6,-10,]),'EQUALS':([2,],[3,]),'LCORCHETE':([3,],[7,]),'NUMBER':([3,7,10,11,12,13,],[9,9,9,9,9,9,]),'PLUS':([4,6,8,9,17,18,19,20,],[10,-4,-7,-12,-2,-3,-5,-6,]),'MINUS':([4,6,8,9,17,18,19,20,],[11,-4,-7,-12,-2,-3,-5,-6,]),'TIMES':([6,8,9,17,18,19,20,],[12,-7,-12,12,12,-5,-6,]),'DIVIDE':([6,8,9,17,18,19,20,],[13,-7,-12,13,13,-5,-6,]),'RCORCHETE':([7,9,15,16,],[14,-12,21,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assign':([0,],[1,]),'expr':([3,],[4,]),'list':([3,],[5,]),'term':([3,10,11,],[6,17,18,]),'factor':([3,7,10,11,12,13,],[8,16,8,8,19,20,]),'element':([7,],[15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assign","S'",1,None,None,None),
  ('assign -> NAME EQUALS expr','assign',3,'p_assign','semantica.py',7),
  ('expr -> expr PLUS term','expr',3,'p_expr','semantica.py',10),
  ('expr -> expr MINUS term','expr',3,'p_expr','semantica.py',11),
  ('expr -> term','expr',1,'p_expr','semantica.py',12),
  ('term -> term TIMES factor','term',3,'p_term','semantica.py',15),
  ('term -> term DIVIDE factor','term',3,'p_term','semantica.py',16),
  ('term -> factor','term',1,'p_term','semantica.py',17),
  ('assign -> NAME EQUALS list','assign',3,'p_lista','semantica.py',20),
  ('list -> LCORCHETE RCORCHETE','list',2,'p_list','semantica.py',23),
  ('list -> LCORCHETE element RCORCHETE','list',3,'p_list','semantica.py',24),
  ('element -> factor','element',1,'p_element','semantica.py',27),
  ('factor -> NUMBER','factor',1,'p_factor','semantica.py',30),
]
